### ISSUE TITLE
error in highest weight CGC

### ISSUE THREAD

**Issue by Jutho** [maartenvd/SUNRepresentations.jl#1]
https://github.com/maartenvd/GTP_CGC/blob/bf9d148d7b42e3c945c858142410f651a021cde3/cgc.jl#L55

This does not seem correct. You just seem to add all the different contributions of different creation operators together, whereas acting with J+^ell = J+^ell_S1 + J+^ell_S2 for every single value of ell gives an independent set of equations. I am actually surprised this worked in its current form, unless I am overlooking something?

**Comment by maartenvd** [comment]
Oh indeed, that is totally incorrect. I'll try to correct it

**Comment by maartenvd** [comment]
Both highest and lower weight cgcs suffer from this problem. This makes sense, because i tried to rewrite / clean up the code a bit and everything broke. Its a wonder that the tensorkit tests passed partially, and the comparisons to matlab worked

**Comment by Jutho** [comment]
Don't spend time on this during your holidays; I am anyway working on some changes. I hope I can send you something before I leave on holidays.

**Comment by maartenvd** [comment]
lower weight cgc turned out not to have that problem. I have rewritten both, but the errors in tensorkit persist. I will first compare with what bram gets to make sure my clebsch gordans are correct

**Comment by Jutho** [comment]
Hi Maarten; did you get my email. It contained the start of an implementation with some (possible) improvements. Slicing a SparseArray used to return a dense array, this should now be fixed with the latest master of TensorOperations. But even then, `enumerate` on this `SparseArray` will loop over all indices, also the ones with zero values. I've added a `nonzeros` function to loop over nonzero index - value pairs . Also, in the current highest way function, you loop over both GT patterns of the two irreps to be fused, while looping over one and then looking up the other in the table is sufficient.

**Comment by maartenvd** [comment]
ah no, I was afraid to open my mails after going on holiday, so I put it
off. I was going to be lazy and include all gtpatterns as a field in the
Irrep{N} structure, making iterating over the patterns zero-cost.

it is nicer now, and everything should work again. I tested with tensorkit
and again there goes something wrong with norm conservation after
permutations.

I did change the gaugefixing back, because I don't think the new version is
correct. At the very least, my lowest weight CGC method fails to give
unitary cgc after using the new gauge fixing, while it worked nicely
together with the previous one.

Op di 22 sep. 2020 om 08:59 schreef Jutho <notifications@github.com>:
